using Microsoft.ML.Data;

namespace WebApplicationAPI.ML;

/// <summary>
/// Represents the output prediction results generated by the bot detection classification model.
/// </summary>
public class BotPrediction
{
    /// <summary>
    /// Gets or sets a value indicating whether the request pattern is classified as a bot attack.
    /// </summary>
    [ColumnName("PredictedLabel")]
    public bool IsBotOrAttack { get; set; }

    /// <summary>
    /// Gets or sets the calculated probability score ranging from 0.0 to 1.0.
    /// </summary>
    public float Probability { get; set; }

    /// <summary>
    /// Gets or sets the raw classification decision score.
    /// </summary>
    public float Score { get; set; }
}